# Generated by Django 6.0 on 2025-12-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='product/default.jpg', null=True, upload_to='product/'),
        ),
    ]
