# Generated by Django 6.0 on 2025-12-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_comments_product_alter_comments_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='rate',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
